name: image_gallery_saver
description: A new flutter plugin project for save image to gallery, iOS need to add the following keys to your Info.plist file.
version: 2.0.0
homepage: https://gitlab.brainco.cn/flutter/image_gallery_saver.git
publish_to: http://dart-pub.brainco.cn:8081

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.imagegallerysaver
        pluginClass: ImageGallerySaverPlugin
      ios:
        pluginClass: ImageGallerySaverPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter

